### ISSUE TITLE
Support for context-aware connection

### ISSUE THREAD

**Issue by smotes** [gomodule/redigo#342] opened 2018-05-25 17:32 UTC
Similar to the `ConnWithTimeout` interface that implements the `Do/Receive` methods with an extra `time.Duration` parameter, I think it would be useful to add in a `ConnWithContext` interface that takes an extra `context.Context` parameter. Many other Golang libraries are starting to adopt `context.Context` usage for cancellation since it was put into the standard library. Additionally, this proposed change shouldn't make any breaking changes to this package's public API. I am happy to implement this feature if I get the green light from whoever maintains this package - I just wanted to start up a discussion first per https://github.com/gomodule/redigo/blob/master/.github/CONTRIBUTING.md.

**Comment by redmondnoodle** [comment] 2018-05-27 22:02
What is the actual feature you are proposing?  I understand you want to add a context argument, but what do you plan to do with that argument?

**Comment by smotes** [comment] 2018-05-28 15:39
I plan to use it for handling timeouts when hitting the network with the client (in this case, when using `Do`)

**Comment by redmondnoodle** [comment] 2018-05-28 16:14
Because connections are killed on timeout, context deadlines can result in connection thrashing.

In any case, are you asking for this function?

    func DoWithContext(c Conn, ctx context.Context, cmd string, args ...interface{}) (interface{}, error) {
        if t, ok := ctx.Deadline(); ok {
            return DoWithTimeout(c, t.Sub(time.Now()), cmd, args...)
       }
       return c.Do(cmd, args...)
    }

**Comment by smotes** [comment] 2018-05-28 16:45
I was not aware the connection was closed when a timeout error occurred, but I am seeing that locally now after some testing. Is that intended behavior in this package? Imho it seems a bit much to have to create a new connection each time one of its operations times out. And yes, the snippet you posted above is basically what I had in mind with the code additions.

**Comment by redmondnoodle** [comment] 2018-05-28 17:21
My company uses conservative timeouts to detect dead network connections and servers.  Closing the connection is the right thing to do when these conservative timeouts are breached.

Closing the connection on context timeout or cancelation is a bit much.  Perhaps the code can be updated to handle timeout and cancelation like the Go libraries that have adopted `context.Context`.

**Comment by smotes** [comment] 2018-05-28 17:45
I agree - in general it seems like the Redis client shouldn't close by default on cancellations/timeouts, but rather leave that to the calling code to handle the situation as it sees fit. It might be worth it to update the `DoWithTimeout` code too for the sake of consistency.

**Comment by redmondnoodle** [comment] 2018-05-28 18:05
I think I see why the connection is made unusable after timeout. If a response is not completely read because of a timeout, then the connection will be out of "sync".   How do other libraries handle this?

**Comment by redmondnoodle** [comment] 2018-05-28 19:00
Although the mediocregopher/radix.v2 does not close the connection in all cases, the connection is not useable after a timeout error.  If the timeout is [on line 144](https://github.com/mediocregopher/radix.v2/blob/364a4ea87c50d1b3d58e2af8199d9ef0e145a51d/redis/resp.go#L144), then the next command will read the abandoned response.  If the timeout is in [lines 149-160](https://github.com/mediocregopher/radix.v2/blob/364a4ea87c50d1b3d58e2af8199d9ef0e145a51d/redis/resp.go#L149-L160), then next command will begin reading the partially consumed response.  In both cases, the client gets out of sync with the data it's reading from the wire.

**Comment by garyburd** [comment] 2018-06-01 13:17
What is the problem you are trying to solve?  

You said that you want handle timeouts. Read and write timeouts can be specified when dialing a connection and the application can override the read timeout on a per-call basis.  Explain why this does not meet your needs.

It may be that adding a context argument is part of fixing the problem, but let's start with a discussion of the problem.

**Comment by smotes** [comment] 2018-06-01 13:59
The problem I'm trying to solve is cancellation, where timeouts are just a special case. The `context.Context` interface exposes a `Done() <-chan struct{}` method to check when cancellation has occurred and `Err() error` to check the related error, but that error value doesn't necessarily have to be from a timeout (for instance, it could be via `context.WithCancel` after catching a SIGINT from the OS and gracefully stopping a goroutine). Many other parts of the Go stdlib are now using this approach in addition to exposing old timeout `time.Duration` values in the API, such as `net/http` and `database/sql`.

**Comment by garyburd** [comment] 2018-06-01 14:23
Describe the specific problem you are trying to fix in your application.  I know what context does. There's no need to repeat a description here.

**Comment by smotes** [comment] 2018-06-01 14:31
I'm working with a multi-stage pipeline where stage 3 involves using Redis as a cache to detect duplicate values, but is dependent on other stages still running to continue. If another stage fails at some point during runtime, I'd like to be able to initiate early cancellation on all other stages without waiting for each of their long-running tasks to end.

**Comment by garyburd** [comment] 2018-06-01 15:07
Redis does not provide a way to cancel a command.  Which Redis command is taking so long that it's a concern?   Are you using one of the blocking commands?

**Comment by smotes** [comment] 2018-06-01 15:23
No blocking commands, just basic stuff like `GET` and `SETEX`. It's more a matter of uniformity for me - where all other parts of my application take `context.Context` for cancellations, and I thought it would be a nice addition to this package's API.

**Comment by redmondnoodle** [comment] 2018-06-01 15:49
An earlier [comment](https://github.com/gomodule/redigo/issues/342#issuecomment-392557457) requests a timeout on `Do`.  More recent comments say the issue is cancelation. ?????

**Comment by smotes** [comment] 2018-06-01 15:52
Misclicked the close button when replying, sorry.

I am also setting timeouts as we discussed earlier (but currently I can already do that separately by just using the `DoWithTimeout` function, but was just making a further argument for `context` as it could be more generalized in my program's layout.

**Comment by garyburd** [comment] 2018-06-01 16:43
Is there a Redis command that you need to cancel?

**Comment by garyburd** [comment] 2018-06-01 19:36
@redmondnoodle  I do not recommend your proposed `DoWithContext` function.  If the context timeout is less than the time needed to execute a command, then the connection times out and is no longer useable.  If the context timeout is much greater than expected time to execute the command, then it takes longer to detect that the server is down or the network connection is broken.

**Comment by garyburd** [comment] 2018-06-04 18:56
I am closing this issue because there's not a strong argument for a new feature.  Although the application stages may be long running, individual calls to GET and SETEX are not.  The application can terminate a stage without involving this package.   The dial timeout options handle timeouts for GET and SETEX commands.

There's no need to change the API when there are no features to add.

**Closed by garyburd** 2018-06-04 18:56 UTC

**Comment by pennersr** [comment] 2018-06-26 21:00
@garyburd I have this use case: a goroutine is spawned waiting for something to happen by means of a "BRPOP key 0" (0 -- so no timeout). Now, as @smotes mentions above as well, I need to do a graceful shutdown after receiving SIGINT. The usual way of doing this is to use a context. Without having a context in place, how can the goroutine doing the BRPOP be properly signalled to stop what it is doing?

**Comment by garyburd** [comment] 2018-06-27 15:23
@pennersr See #351.

**Comment by pennersr** [comment] 2018-06-27 15:41
@garyburd While the DoWithCancel() from #351 could be used to implement my use case, that approach does result in each of my Do() commands to have an extra overhead/latency for the additional Redis commands to obtain the client ID -- something that would not be necessary if there was "native" support for cancelling any ongoing command in a Redis connection.

FWIW, I have now implemented my use case by rather bluntly issuing a conn.Close() when the cancel is triggered. This aborts the ongoing Do("BRPOP"), albeit with an error:

```
2018/06/26 21:49:48 Error BRPOP:read tcp 172.19.0.6:58856->172.19.0.3:6379: use of closed network connection
```

**Comment by garyburd** [comment] 2018-06-27 16:31
Extra roundtrips to the server can be eliminated by caching the result of the CLIENT ID command in the low-level connection. I updated 351 to mention this.

Native support cannot eliminate the overhead of coordinating with a goroutine to wait on the context done channel.  I proposed DoWithCancel() as a separate helper so that applications incur this extra overhead only where needed.
