### ISSUE TITLE
Expose DialOptions used to create the connection to support instrumentation/tracing features  

### ISSUE THREAD

**Issue by rarguelloF** [gomodule/redigo#642] opened 2023-03-07 16:50 UTC
Hi 👋 

I was wondering if it would be possible to expose the `dialOptions` that were used during any of the `Dial*` functions to support instrumentation/tracing libraries like [OpenTelemetry](https://opentelemetry.io/).

As an example, they state Redis instrumentations should at least provide the `db.redis.database_index` field ([ref](https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/database/#call-level-attributes-for-specific-technologies)), which is currently inaccessible since this struct and fields are unexported.

If this sounds good to you, I'm happy to open a PR implementing this change.

Thanks!

**Comment by stevenh** [comment] 2023-03-08 17:08
Nope this doesn't currently track the connection DB. I'd even go so far as to say calling `SELECT` manually will result in unpredictable results due to the pooled nature of the connections, so while it's not prevented doing so would be dangerous.

**Comment by rarguelloF** [comment] 2023-03-10 13:37
@stevenh in that case what would be the best approach to support this kind of instrumentation in this library?

**Comment by stevenh** [comment] 2023-08-20 11:16
I would write a wrapper to achieve that, I wouldn't add it directly as many people don't need to want it as it would be performance hit, all be it small.

**Comment by andotorg** [comment] 2023-10-27 07:43
What every time support opentelemetry?

**Comment by stevenh** [comment] 2023-10-28 21:22
> What every time support opentelemetry?

Not sure I understand the question, could you clarify?

**Comment by stevenh** [comment] 2024-01-28 14:45
This is related to a similar conversation about adding slog support, which has me thinking about a [v2 to support easier extension](https://github.com/gomodule/redigo/issues/656#issuecomment-1913298826) which should consider this use case as well.

Would like to peoples thoughts on that as an approach?

**Comment by stevenh** [comment] 2024-01-28 14:56
Thinking more about this, if we could enable connection wrapping using dial options that would allow users to enable tracing and logging with zero overhead for others, something to consider.

**Comment by stevenh** [comment] 2024-01-28 14:58
Going to close this as a duplicate of #568 we can continue this conversation there.

**Closed by stevenh** 2024-01-28 14:58 UTC
Labels: Enhancement
