### ISSUE TITLE
go.mod versioning issues

### ISSUE THREAD

**Issue by pkieltyka** [gomodule/redigo#556] opened 2021-03-11 00:47 UTC
Hi there, sadly you have fallen into the trap of go modules versioning. You've tagged v2.0.0 without a go.mod file, but your master has https://github.com/gomodule/redigo/blob/master/go.mod which doesn't reference /v2 -- therefore, it makes it very difficult to use the latest version of this library.

**Comment by pkieltyka** [comment] 2021-03-11 00:49
I suggesting removing the v2.0.0 tag from git, and never-ever switching to v2.x.x, and stay within v1.x or face the great pains of Go modules and developer experience swamp

**Comment by stevenh** [comment] 2021-03-15 00:14
Doing that would cause regressions for others. There's a lot of discussion about why we took the route we did in the [gomod pr](https://github.com/gomodule/redigo/pull/440)

Using the latest version is easy in a go module enabled but just in case you didn't realise v2 was like pre-release and is not maintained.

**Comment by dprosper** [comment] 2021-04-26 14:26
I fell into the trap as well, the main problem is `go get github.com/gomodule/redigo/redis` as documented in the readme, defaults you to the V2.0.0 version and it took a while for me to realize why some things were not workin :-(

**Comment by stevenh** [comment] 2021-04-27 11:24
I can't reproduce that @dprosper what version of go did you use in your case, here's what I saw when I tested
```shell
~/code/tst$ go version
go version go1.16 linux/amd64
~/code/tst$ go mod init example.com/m
go: creating new go.mod: module example.com/m
~/code/tst$ go get github.com/gomodule/redigo/redis
go: downloading github.com/gomodule/redigo v1.8.4
go: downloading github.com/gomodule/redigo/redis v0.0.0-do-not-use
go get: added github.com/gomodule/redigo v1.8.4
```

**Comment by dprosper** [comment] 2021-04-27 12:06
@stevenh Thank you for trying it out and your steps to attempt at reproducing.  I went back and tried it with a new project and it worked fine exactly has you have it above.  So on to figuring out what went wrong for me last week.  I was using an existing project, so tracing back my steps I found the following steps should result in the issue I saw

```
dimitriprosper@dimitris-mbp tstb % go version
go version go1.16.3 darwin/amd64

dimitriprosper@dimitris-mbp tstb % go mod init example.com/b              
go: creating new go.mod: module example.com/b

dimitriprosper@dimitris-mbp tstb % go get github.com/gin-contrib/sessions 
go get: added github.com/gin-contrib/sessions v0.0.3

dimitriprosper@dimitris-mbp tstb % go get github.com/gomodule/redigo/redis

dimitriprosper@dimitris-mbp tstb % cat go.mod
module example.com/b

go 1.16

require (
        github.com/gin-contrib/sessions v0.0.3 // indirect
        github.com/gomodule/redigo v2.0.0+incompatible // indirect
)
```

So it looks like the problem is coming from using `github.com/gin-contrib/sessions`

**Comment by stevenh** [comment] 2021-04-27 12:36
Yer looks like sessions is the cause, you can see it here https://github.com/gin-contrib/sessions/blob/master/go.mod

I would encourage you to raise a bug with that repo, likely they did that before we made redigo go mod compatible.

**Comment by stevenh** [comment] 2021-06-10 09:56
Looks like sessions uses that because its dependency https://github.com/boj/redistore does too. I've put in a PR to fix that https://github.com/boj/redistore/pull/63 but the repo doesn't seem to be very active so we'll have to wait and see.

The workaround in the mean time is to add a replace line for redigo e.g.
```
go mod edit -replace github.com/gomodule/redigo@v2.0.0+incompatible=github.com/gomodule/redigo@v1.8.4
```

**Comment by stevenh** [comment] 2021-06-10 09:58
As this is an external issue and workaround has been suggested closing this issue.

**Closed by stevenh** 2021-06-10 09:58 UTC
