### ISSUE TITLE
redigo does NOT support `ZPOPMAX` & ` ZPOPMIN` which are introduced in stable version 5.0.0

### ISSUE THREAD

**Issue by steven-zou** [gomodule/redigo#417] opened 2019-04-12 03:06 UTC
redigo does NOT support `ZPOPMAX` & ` ZPOPMIN` which are introduced in stable version 5.0.0

**Comment by stevenh** [comment] 2019-04-12 09:09
This just looks like a normal redis command with not special handling, so it should just work.

Do you have an example of the error you're seeing?

**Comment by timakin** [comment] 2019-04-16 08:52
Are you sure?
It properly works for me.

```
package main

import (
	"fmt"

	"github.com/gomodule/redigo/redis"
)

func main() {
	conn, err := redis.Dial("tcp", "localhost:6379")
	if err != nil {
		panic(err)
	}
	defer conn.Close()

	for k, v := range map[int]string{
		1: "one",
		2: "two",
		3: "three",
	} {
		r, err := conn.Do("ZADD", "myzset", k, v)
		if err != nil {
			panic(err)
		}
		fmt.Println(r)
	}

	maxbyteslice, err := redis.ByteSlices(conn.Do("ZPOPMAX", "myzset"))
	if err != nil {
		panic(err)
	}
	fmt.Printf("maxbyteslice= %s\n", maxbyteslice)

	minbyteslice, err := redis.ByteSlices(conn.Do("ZPOPMIN", "myzset"))
	if err != nil {
		panic(err)
	}
	fmt.Printf("minbyteslice= %s\n", minbyteslice)

	for k, v := range map[int]string{
		1: "one",
		2: "two",
		3: "three",
	} {
		r, err := conn.Do("ZADD", "myzset", k, v)
		if err != nil {
			panic(err)
		}
		fmt.Println(r)
	}

	maxval, err := redis.Values(conn.Do("ZPOPMAX", "myzset"))
	if err != nil {
		panic(err)
	}
	var maxk int
	var maxv string
	maxval, _ = redis.Scan(maxval, &maxv, &maxk)
	fmt.Printf("maxk= %+v, maxv= %+v\n", maxk, maxv)

	minval, err := redis.Values(conn.Do("ZPOPMIN", "myzset"))
	if err != nil {
		panic(err)
	}
	var mink int
	var minv string
	minval, _ = redis.Scan(minval, &minv, &mink)
	fmt.Printf("mink= %+v, minv= %+v\n", mink, minv)
}
```

```
$ go run main.go
1
1
1
maxbyteslice= [three 3]
minbyteslice= [one 1]
1
0
1
maxk= 3, maxv= three
mink= 1, minv= one
```

**Comment by stevenh** [comment] 2019-04-17 09:32
Based on that I'm going to close this issue, if you can reproduce the error you were having @steven-zou feel free to reply / re-open the bug.

**Closed by stevenh** 2019-04-17 09:32 UTC
